name: HungerGames
main: main.java.me.MnomisC.HG.HungerGames
version: 1.0
depend: [Multiverse-Core]
description: >
  Hungergames plugin
commands:
 hungergames:
   description: Hungergames main
 hg:
   description: Hungergames main

permissions:
  hungergames.admin:
    description: All admin commands
    default: false
  