name: HungerGames
main: main.java.me.MnomisC.HG.HungerGames
version: 1.0
description: >
  Hungergames plugin
commands:
 hungergames:
   description: Hungergames main
   usage: /hungergames (command) (args)
 hg:
   description: Hungergames main
   usage: /hg (command) (args)

permissions:
  hungergames.admin:
    description: All admin commands
    default: false
  